# Generated by Django 4.2.1 on 2023-05-14 14:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_card', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=512)),
                ('include_ratings', multiselectfield.db.fields.MultiSelectField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('heirloom', 'Heirloom'), ('event', 'Event')], max_length=32)),
                ('ratings_rule', models.CharField(default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('is_by_series', models.BooleanField(default=False)),
                ('is_by_event', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=1024)),
                ('price', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='card_pack_images')),
                ('include_character_cards', models.ManyToManyField(blank=True, related_name='included_character_cards', to='character_card.charactercard')),
                ('include_series', models.ManyToManyField(blank=True, related_name='included_series', to='series.serie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
