# Generated by Django 4.2.1 on 2023-05-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card_pack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('card_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_card_pack', to='card_pack.cardpack')),
                ('character_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_character_card', to='character_card.charactercard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
