# Generated by Django 4.2.1 on 2023-05-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_en', models.CharField(default='', max_length=512)),
                ('name_jp', models.CharField(default='', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
